/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InformacionGeneral: typeof import('./src/components/InformacionGeneral.vue')['default']
    InformacionGeneralPaciente: typeof import('./src/components/InformacionGeneralPaciente.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MiPlan: typeof import('./src/components/MiPlan.vue')['default']
    Navbar: typeof import('./src/components/layouts/Navbar.vue')['default']
    Paciente: typeof import('./src/components/InformacionGeneral Paciente.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    PanelNutricionista: typeof import('./src/components/PanelNutricionista.vue')['default']
    PanelPaciente: typeof import('./src/components/PanelPaciente.vue')['default']
    PerfilProfesional: typeof import('./src/components/PerfilProfesional.vue')['default']
    PerfilSalud: typeof import('./src/components/PerfilSalud.vue')['default']
    PerfilUsuario: typeof import('./src/components/PerfilUsuario.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
