/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/acompanamiento': RouteRecordInfo<'/acompanamiento', '/acompanamiento', Record<never, never>, Record<never, never>>,
    '/crearPaciente': RouteRecordInfo<'/crearPaciente', '/crearPaciente', Record<never, never>, Record<never, never>>,
    '/crearplan': RouteRecordInfo<'/crearplan', '/crearplan', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/food': RouteRecordInfo<'/food', '/food', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/pacientes': RouteRecordInfo<'/pacientes', '/pacientes', Record<never, never>, Record<never, never>>,
    '/perfil': RouteRecordInfo<'/perfil', '/perfil', Record<never, never>, Record<never, never>>,
    '/planes': RouteRecordInfo<'/planes', '/planes', Record<never, never>, Record<never, never>>,
    '/planesPaciente': RouteRecordInfo<'/planesPaciente', '/planesPaciente', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/registroPacientes': RouteRecordInfo<'/registroPacientes', '/registroPacientes', Record<never, never>, Record<never, never>>,
  }
}
